[package]
name = "speedy2d"
version = "0.1.0"
authors = ["Anshuman <amedhi@connect.ust.hk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
